version: "3"
services:
  todo:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      MONGODB_URI: "mongodb://mongo:27017/todo_items"
    command: npm start

  mongo:
    image: mongo
    ports:
      - "27017:27017"

